/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Contoladores.ControladorUsuario;
import Modelos.Usuarios;
import Modelos.UsuariosConsulta;
import Modelos.textoSombra;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.text.html.CSS;

/**
 *
 * @author domin
 */
public class LoginForm extends javax.swing.JFrame {
    
    Usuarios usuarios = new Usuarios();
    UsuariosConsulta consulta = new UsuariosConsulta();
    
 
    
    public LoginForm() {
        initComponents();
        
        

        txtusuario.setOpaque(false);
        txtClave.setOpaque(false);
        textoSombra usuario = new textoSombra("Ingrese su usuario", txtusuario);
        textoSombra clave = new textoSombra("Ingrese su contraseña", txtClave);
        
        ControladorUsuario controladorUsuario = new ControladorUsuario(this, usuarios, consulta);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelLog = new javax.swing.JPanel();
        checkRecodar = new javax.swing.JCheckBox();
        loginLoader = new javax.swing.JProgressBar();
        txtusuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnLogin1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(224, 231, 255));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLog.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkRecodar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkRecodar.setForeground(new java.awt.Color(150, 150, 150));
        checkRecodar.setText("Recuérdame");
        checkRecodar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        checkRecodar.setBorderPainted(true);
        checkRecodar.setContentAreaFilled(false);
        checkRecodar.setFocusPainted(false);
        jPanelLog.add(checkRecodar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        loginLoader.setBackground(new java.awt.Color(242, 243, 244));
        loginLoader.setForeground(new java.awt.Color(59, 140, 237));
        jPanelLog.add(loginLoader, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 140, 0));

        txtusuario.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtusuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtusuario.setForeground(new java.awt.Color(30, 30, 30));
        txtusuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtusuario.setToolTipText("");
        txtusuario.setBorder(null);
        txtusuario.setOpaque(true);
        txtusuario.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtusuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtusuarioMouseExited(evt);
            }
        });
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        jPanelLog.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 340, 40));

        txtClave.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtClave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtClave.setForeground(new java.awt.Color(0, 0, 0));
        txtClave.setToolTipText("");
        txtClave.setBorder(null);
        txtClave.setInheritsPopupMenu(true);
        txtClave.setOpaque(true);
        txtClave.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });
        jPanelLog.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 340, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Login_1.png"))); // NOI18N
        jPanelLog.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 600));
        jPanelLog.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, -1, -1));

        jLabel2.setBackground(new java.awt.Color(30, 58, 138));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 58, 138));
        jLabel2.setText("GraduaciónUP ");
        jPanelLog.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 255));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 255));
        jPanelLog.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 300, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        jPanelLog.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 20, 30));
        jPanelLog.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, 30));

        jSeparator3.setBackground(new java.awt.Color(204, 204, 255));
        jSeparator3.setForeground(new java.awt.Color(204, 204, 255));
        jPanelLog.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 300, 20));

        btnLogin1.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnLogin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Frame 10_1.png"))); // NOI18N
        btnLogin1.setAutoscrolls(true);
        btnLogin1.setBorder(null);
        btnLogin1.setBorderPainted(false);
        btnLogin1.setContentAreaFilled(false);
        btnLogin1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLogin1.setFocusPainted(false);
        btnLogin1.setOpaque(true);
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });
        jPanelLog.add(btnLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 370, 70));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lock.png"))); // NOI18N
        jPanelLog.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 30, 30));
        jPanelLog.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 40, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-graduation-cap-60.png"))); // NOI18N
        jPanelLog.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Sistema de Gestión de Documentos Universitarios");
        jPanelLog.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 310, -1));

        jPanel1.add(jPanelLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 853, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1381, 772));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
   txtClave.requestFocus();
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void txtusuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusuarioMouseEntered
      
    }//GEN-LAST:event_txtusuarioMouseEntered

    private void txtusuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusuarioMouseExited

    }//GEN-LAST:event_txtusuarioMouseExited

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnLogin1;
    private javax.swing.JCheckBox checkRecodar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelLog;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JProgressBar loginLoader;
    public javax.swing.JPasswordField txtClave;
    public javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
