/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;
import Modelos.SolicitudDatos;
import Modelos.textoSombra;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;


import javax.swing.JFileChooser;

/**
 *
 * @author domin
 */
public class SolicitudesForm extends javax.swing.JFrame {

    /**
     * Creates new form DocumentosForm
     */
    public SolicitudesForm() {
        initComponents();
        TxtSolicitud.setOpaque(false);
        textoSombra sombra = new textoSombra("Describe tu solicitud de revision...", TxtSolicitud);

        int id = 2;
        SolicitudDatos datos = new SolicitudDatos();
        datos.cargarSolicitudes(id, JtableDatos);

    }
 private String url; // Ruta del archivo seleccionado


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnCerrarSesion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelmenu = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtRuta = new javax.swing.JLabel();
        TxtSolicitud = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtableDatos = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(224, 231, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnCerrarSesion.setBackground(new java.awt.Color(96, 165, 250));
        BtnCerrarSesion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        BtnCerrarSesion.setText("Cerrar Sesión");
        BtnCerrarSesion.setBorder(null);
        BtnCerrarSesion.setBorderPainted(false);
        BtnCerrarSesion.setContentAreaFilled(false);
        BtnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnCerrarSesion.setFocusPainted(false);
        BtnCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BtnCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 30, 140, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Graduacion_1.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 60));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(219, 234, 254));
        jLabel5.setText("Tu Camino Hacia la Graduación");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, 20));

        jLabel4.setBackground(new java.awt.Color(30, 58, 138));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GraduaciónUP ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar Sesion_1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 190, -1));

        jLabelmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Barra.png"))); // NOI18N
        jPanel1.add(jLabelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 91));

        jPanel2.setBackground(new java.awt.Color(147, 197, 253));
        jPanel2.setForeground(new java.awt.Color(245, 158, 11));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1370, 8));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-return-25.png"))); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-sent-25.png"))); // NOI18N
        jButton3.setText("Enviar Solicitud");
        jButton3.setBorder(null);
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 1170, 60));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-send-25.png"))); // NOI18N
        jLabel18.setText("Nueva Solicitud de Revisión");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 350, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Envía una solicitud para que revisen tus documentos subidos");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 47, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Descripción de la Solicitud");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 30));

        txtRuta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRuta.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(txtRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 230, 280, 50));

        TxtSolicitud.setBackground(new java.awt.Color(255, 255, 255));
        TxtSolicitud.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtSolicitud.setForeground(new java.awt.Color(0, 0, 0));
        TxtSolicitud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        TxtSolicitud.setCaretColor(new java.awt.Color(0, 0, 0));
        TxtSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSolicitudActionPerformed(evt);
            }
        });
        jPanel3.add(TxtSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 1150, 80));

        JtableDatos.setBackground(new java.awt.Color(255, 255, 255));
        JtableDatos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JtableDatos.setForeground(new java.awt.Color(51, 51, 51));
        JtableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JtableDatos.setGridColor(new java.awt.Color(255, 255, 255));
        JtableDatos.setSelectionBackground(new java.awt.Color(204, 204, 255));
        JtableDatos.setSelectionForeground(new java.awt.Color(29, 78, 216));
        jScrollPane1.setViewportView(JtableDatos);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 1150, 120));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 1250, 530));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-clipboard-25.png"))); // NOI18N
        jLabel19.setText("Solicitud de Seguimiento");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 350, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarSesionActionPerformed
        this.dispose();
        LoginForm form = new LoginForm();

        form.setVisible(true);
        form.setLocationRelativeTo(null);
    }//GEN-LAST:event_BtnCerrarSesionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      this.dispose();
      AdminForm adminForm = new AdminForm();
      adminForm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TxtSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSolicitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSolicitudActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrarSesion;
    public javax.swing.JTable JtableDatos;
    private javax.swing.JTextField TxtSolicitud;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelmenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtRuta;
    // End of variables declaration//GEN-END:variables
}
